### ISSUE TITLE
[SUGGESTION]: Change Organization Location

### ISSUE THREAD

**Issue by TechStudent10** [collab-community/.github#2]
Not everyone is located in India. I know the founder is in India, but I think a more accurate location would be "Earth" or something like that.

**Comment by KendallDoesCoding** [comment]
Hi,

We actually have a discord server with 209 of them, and I believe 99.9% if not 100% of them are from India, and they will slowly join this GitHub organization.

Further, this organization was founded in India, hence we marked it as India.

Even @apple, they got it set as their HQ location, so India in a way is our communities HQ.

But, this is just my opinion, it's up to @Adarsh-jaiss!

**Comment by Adarsh-jaiss** [comment]
-- I think we should keep it india

**Comment by KendallDoesCoding** [comment]
> -- I think we should keep it india

@Adarsh-jaiss Thanks for your input.
